### ISSUE TITLE
Improve UI scaling

### ISSUE THREAD

**Issue by CamoRF** [rfg-modding/Nanoforge#68]
* On higher scaling the UI doesn't work very well, can't click "Maps" for example

**Comment by Moneyl** [comment]
Will need to investigate this again post v1.0.0. To start we can get it looking good on all the common resolutions like 1080P, 2K, and 4K. I do most of my development on a 2K monitor with no DPI scaling so it should always look decent at that resolution. Probably not worth it supporting anything less than 1080P.

Preliminary testing at 4K on the current version of the rewrite:
- With no DPI scaling its way too small. Might be able to fix this by regenerating the fonts whenever the window is resized.
- With DPI scaling set to 200% in windows it looks fine. 
- The UI library NF uses, Dear ImGui, has some DPI scaling options. I'll need to read about them more and test them to see if they're worth using.

**Comment by CamoRF** [comment]
I use 125% DPI scaling in Windows at 4k if that helps

**Comment by CamoRF** [comment]
It actually seems okay in the C++ version, will comment if I run into any issues again.
