### ISSUE TITLE
Change map names to reflect their in game names in map list

### ISSUE THREAD

**Issue by CamoRF** [rfg-modding/Nanoforge#86]
For the maps that come with the game we should change the name in bold text to reflect the in game name for the following maps:

- Doubletime : mpcx_crossover
- Outpost : mpcx_assembly

**Comment by CamoRF** [comment]
![Image](https://user-images.githubusercontent.com/113881920/235269680-34a91088-a5c7-4bc1-ac21-715f8086c2df.png)

**Comment by Moneyl** [comment]
Do you know where it's getting that name from?

**Comment by CamoRF** [comment]
> Do you know where it's getting that name from?

`<Name>Cross Over</Name>` in `mp_levels.xtbl`

**Comment by CamoRF** [comment]
I'm closing this issue since I can easily change their names in the Terraform Patch without it breaking anything, that'll save you the trouble.
