### ISSUE TITLE
Pre v1.0.0 release testing

### ISSUE THREAD

**Issue by Moneyl** [rfg-modding/Nanoforge#96]
Once #30 and #36 are done map import will be mostly ported. Next we need to make sure it works on all the vanilla maps:
- [x] Make sure every single MP/WC map imports correctly.
- [x] Make sure every single MP/WC map loads from serialized project data correctly.
- [x] Install latest version of terraform patch and make sure that maps all load in that case as well.
- [x] Make sure custom maps like Warehouse and Junkyard can be opened, edited, and exported:
    - [x] Import
    - [x] Saving and loading projects
    - [x] Reloading project and opening map that's already been imported
    - [x] Export
    - [x] Re-import an exported vpp for these maps and make sure it's correct.

**Comment by CamoRF** [comment]
Would it be a good idea to install the Terraform Patch and test importing entirely new map files to make sure those are supported now?

**Comment by Moneyl** [comment]
Yes. Good idea. Added to list.

**Comment by Moneyl** [comment]
Tested opening every single vanilla map. After a few bug fixes it's working. Gonna hold off testing Terraform Patch maps until after #42 and #81 are done. I want to be able to test loading the maps saved in a project. Completing those should also remove the last of the hardcoded dev paths so you and others can test NF out.
